const chat=document.querySelector('#chat'),input=document.querySelector('#input'),form=document.querySelector('#form'),sendButton=document.querySelector('#send'),clearButton=document.querySelector('#clear'),exportButton=document.querySelector('#export'),status=document.querySelector('#status'),modeButton=document.querySelector('#mode'),searchInput=document.querySelector('#search');
const STORAGE_KEY='karicimgpt-messages',MODE_KEY='karicimgpt-agent',MAX_MESSAGES=50,CLIENT_TIMEOUT_MS=65000;
let messages=load(),agent=localStorage.getItem(MODE_KEY)==='1';
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v.filter(m=>(m?.role==='user'||m?.role==='assistant')&&typeof m?.content==='string').slice(-MAX_MESSAGES):[]}catch{return[]}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(messages.slice(-MAX_MESSAGES)))}
function setMode(v){agent=v;localStorage.setItem(MODE_KEY,v?'1':'0');modeButton.textContent=`Agent: ${v?'Açık':'Kapalı'}`;modeButton.classList.toggle('agent-on',v);modeButton.setAttribute('aria-pressed',String(v));setStatus(v?'Agent modu açık. Web araştırması gerektiğinde kullanılabilir.':'Normal sohbet modu.')}
function escapeHtml(s){return s.replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function formatText(s){return escapeHtml(s).replace(/```([\s\S]*?)```/g,'<pre><code>$1</code></pre>').replace(/\n/g,'<br>')}
function render(){chat.replaceChildren();const q=(searchInput?.value||'').trim().toLocaleLowerCase('tr-TR');const visible=messages.map((m,i)=>({...m,index:i})).filter(m=>!q||m.content.toLocaleLowerCase('tr-TR').includes(q));if(!visible.length){const e=document.createElement('div');e.className='empty';const t=document.createElement('strong');t.textContent=messages.length?'Sonuç yok':'KaricimGPT';const s=document.createElement('span');s.textContent=messages.length?'Aramanla eşleşen mesaj bulunamadı.':agent?'Agent modu açık.':'Ücretsiz AI ile sohbet et.';e.append(t,s);chat.append(e);return}for(const m of visible){const e=document.createElement('article');e.className=`msg ${m.role}`;e.dataset.index=m.index;const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'Sen':'KaricimGPT';const body=document.createElement('div');body.className='content';body.innerHTML=formatText(m.content);const actions=document.createElement('div');actions.className='actions';if(m.role==='assistant'){const copy=document.createElement('button');copy.type='button';copy.textContent='Kopyala';copy.onclick=async()=>{await navigator.clipboard?.writeText(m.content);setStatus('Yanıt kopyalandı.')};actions.append(copy)}const del=document.createElement('button');del.type='button';del.textContent='Sil';del.onclick=()=>{messages.splice(m.index,1);save();render();setStatus('Mesaj silindi.')};actions.append(del);e.append(meta,body,actions);chat.append(e)}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function setStatus(message='',error=false){status.textContent=message;status.className=error?'status error':'status'}
function exportChat(){const payload={app:'KaricimGPT',version:2,exportedAt:new Date().toISOString(),agent,messages};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`karicimgpt-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus('Sohbet dışa aktarıldı.')}
async function ask(){const text=input.value.trim();if(!text||sendButton.disabled)return;messages.push({role:'user',content:text});save();render();input.value='';sendButton.disabled=true;setStatus(agent?'Agent çalışıyor…':'Yanıt hazırlanıyor…');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CLIENT_TIMEOUT_MS);try{const endpoint=agent?'/api/agent':'/api/chat';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({messages}),signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Sunucu hatası (${r.status})`);if(!data.output)throw new Error('Model boş yanıt döndürdü.');messages.push({role:'assistant',content:data.output});save();render();let info=data.model?`Model: ${data.model}`:'Hazır';if(agent&&data.toolCalls>0)info+=` · ${data.toolCalls} araç`;if(data.usedTools||data.webTools)info+=' · web araçları';setStatus(info)}catch(e){setStatus(e.name==='AbortError'?'İstek zaman aşımına uğradı.':(e.message||'Bir hata oluştu.'),true)}finally{clearTimeout(timer);sendButton.disabled=false;input.focus()}}
modeButton.addEventListener('click',()=>{setMode(!agent);render()});form.addEventListener('submit',e=>{e.preventDefault();ask()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});searchInput?.addEventListener('input',render);clearButton.addEventListener('click',()=>{messages=[];save();render();setStatus('Sohbet temizlendi.');input.focus()});exportButton?.addEventListener('click',exportChat);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();input.focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='e'){e.preventDefault();exportChat()}});setMode(agent);render();