const chat=document.querySelector('#chat'),input=document.querySelector('#input'),form=document.querySelector('#form'),sendButton=document.querySelector('#send'),clearButton=document.querySelector('#clear'),status=document.querySelector('#status'),modeButton=document.querySelector('#mode');
const STORAGE_KEY='karicimgpt-messages',MODE_KEY='karicimgpt-agent',MAX_MESSAGES=20,CLIENT_TIMEOUT_MS=65000;
let messages=load(),agent=localStorage.getItem(MODE_KEY)==='1';
function load(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v.filter(m=>(m?.role==='user'||m?.role==='assistant')&&typeof m?.content==='string').slice(-MAX_MESSAGES):[]}catch{return[]}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(messages.slice(-MAX_MESSAGES)))}
function setMode(v){agent=v;localStorage.setItem(MODE_KEY,v?'1':'0');modeButton.textContent=`Agent: ${v?'Açık':'Kapalı'}`;modeButton.classList.toggle('agent-on',v);modeButton.setAttribute('aria-pressed',String(v));setStatus(v?'Agent modu: web araştırması gerektiğinde kullanılabilir.':'Normal sohbet modu.')}
function render(){chat.replaceChildren();if(!messages.length){const e=document.createElement('div');e.className='empty';const t=document.createElement('strong');t.textContent='KaricimGPT';const s=document.createElement('span');s.textContent=agent?'Agent modu açık.':'Ücretsiz AI ile sohbet et.';e.append(t,s);chat.append(e);return}for(const m of messages){const e=document.createElement('div');e.className=`msg ${m.role}`;const meta=document.createElement('div');meta.className='meta';meta.textContent=m.role==='user'?'Sen':'KaricimGPT';e.append(meta,document.createTextNode(m.content));chat.append(e)}window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function setStatus(message='',error=false){status.textContent=message;status.className=error?'status error':'status'}
async function ask(){const text=input.value.trim();if(!text||sendButton.disabled)return;messages.push({role:'user',content:text});save();render();input.value='';sendButton.disabled=true;setStatus(agent?'Agent çalışıyor…':'Yanıt hazırlanıyor…');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CLIENT_TIMEOUT_MS);try{const endpoint=agent?'/api/agent':'/api/chat';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({messages}),signal:controller.signal});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Sunucu hatası (${r.status})`);if(!data.output)throw new Error('Model boş yanıt döndürdü.');messages.push({role:'assistant',content:data.output});save();render();let info=data.model?`Model: ${data.model}`:'Hazır';if(agent&&data.toolCalls>0)info+=` · ${data.toolCalls} araç`;if(data.usedTools)info+=' · web araçları';setStatus(info)}catch(e){setStatus(e.name==='AbortError'?'İstek zaman aşımına uğradı.':(e.message||'Bir hata oluştu.'),true)}finally{clearTimeout(timer);sendButton.disabled=false;input.focus()}}
modeButton.addEventListener('click',()=>{setMode(!agent);render()});form.addEventListener('submit',e=>{e.preventDefault();ask()});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});clearButton.addEventListener('click',()=>{messages=[];save();render();setStatus('Sohbet temizlendi.');input.focus()});setMode(agent);render();
