import http from 'node:http';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import agentHandler from './api/agent.js';
import chatHandler from './api/chat.js';
import memoryHandler from './api/memory.js';
import { heartbeatStatus, startHeartbeat, stopHeartbeat } from './lib/heartbeat.js';
import { memoryHealth } from './lib/memory.js';
import { autonomyHealth, runAutonomyCycle } from './lib/autonomy.js';

const root = path.dirname(fileURLToPath(import.meta.url));
const port = Number(process.env.PORT || 3000);
const startedAt = Date.now();
function headers(res) { res.setHeader('Access-Control-Allow-Origin', process.env.CORS_ORIGIN || '*'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Accept, Authorization'); res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS'); }
function send(res, status, body, type = 'application/json; charset=utf-8') { headers(res); res.statusCode = status; res.setHeader('Content-Type', type); res.end(type.startsWith('application/json') ? JSON.stringify(body) : body); }
async function body(req) { const chunks = []; let size = 0; for await (const chunk of req) { size += chunk.length; if (size > 200_000) throw Object.assign(new Error('Request too large'), { status: 413 }); chunks.push(chunk); } const raw = Buffer.concat(chunks).toString('utf8'); if (!raw) return {}; try { return JSON.parse(raw); } catch { throw Object.assign(new Error('Invalid JSON'), { status: 400 }); } }
function adapter(req, res, parsedBody) { return { ...res, status(code) { res.statusCode = code; return this; }, setHeader(name, value) { res.setHeader(name, value); return this; }, end(data) { res.end(data); }, req, body: parsedBody }; }
async function serveStatic(req, res) { const pathname = req.url === '/' ? '/index.html' : req.url.split('?')[0]; if (!/^\/(?:index\.html|app\.js|sw\.js|manifest\.webmanifest|icon-192\.svg|icon-512\.svg)$/.test(pathname)) return false; try { const file = await readFile(path.join(root, pathname.slice(1))); const type = pathname.endsWith('.js') ? 'text/javascript; charset=utf-8' : pathname.endsWith('.svg') ? 'image/svg+xml' : pathname.endsWith('.webmanifest') ? 'application/manifest+json' : 'text/html; charset=utf-8'; send(res, 200, file, type); return true; } catch { return false; } }
const server = http.createServer(async (req, res) => { headers(res); if (req.method === 'OPTIONS') return send(res, 204, ''); const url = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`); if (req.method === 'GET' && url.pathname === '/health') return send(res, 200, { ok: true, name: 'KaricimGPT Body', uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000), agentConfigured: Boolean(process.env.OPENROUTER_API_KEY || process.env.OPENAI_API_KEY || process.env.XAI_API_KEY), memory: await memoryHealth(), autonomy: await autonomyHealth(), heartbeat: heartbeatStatus(), timestamp: new Date().toISOString() }); if (req.method === 'GET' && url.pathname === '/api/body') return send(res, 200, { name: 'KaricimGPT Body', version: 3, capabilities: ['chat', 'agent', 'web-tools', 'persistent-memory', 'autonomous-learning', 'heartbeat'], safety: { externalWrites: false, shellExecution: false, secretDisclosure: false }, uptimeSeconds: Math.floor((Date.now() - startedAt) / 1000) }); if (req.method === 'GET' && url.pathname === '/api/autonomy') return send(res, 200, await autonomyHealth()); if ((req.method === 'GET' || req.method === 'POST') && url.pathname === '/api/memory') { try { const parsed = req.method === 'POST' ? await body(req) : {}; return await memoryHandler(adapter(req, res, parsed), res); } catch (error) { return send(res, error?.status || 500, { error: error?.message || 'Memory error' }); } } if (req.method === 'POST' && (url.pathname === '/api/chat' || url.pathname === '/api/agent')) { try { const parsed = await body(req); const target = url.pathname === '/api/agent' ? agentHandler : chatHandler; return await target(adapter(req, res, parsed), res); } catch (error) { return send(res, error?.status || 500, { error: error?.message || 'Runtime error' }); } } if (req.method === 'GET' && await serveStatic(req, res)) return; return send(res, 404, { error: 'Not found' }); });
startHeartbeat({ health: async () => { await memoryHealth(); }, memoryMaintenance: async () => { await memoryHealth(); }, autonomyCycle: async () => { await runAutonomyCycle({ health: async () => true, 'regression': async () => true, 'memory-maintenance': async () => Boolean((await memoryHealth()).ok) }); } });
server.listen(port, '0.0.0.0', () => console.log(`KaricimGPT Body listening on ${port}`));
process.on('SIGTERM', () => { stopHeartbeat(); server.close(() => process.exit(0)); });
process.on('SIGINT', () => { stopHeartbeat(); server.close(() => process.exit(0)); });
